# Generated by Django 4.1 on 2022-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_education_school_alter_info_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
