# Generated by Django 4.1 on 2022-09-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_workexperience_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='address',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
