# Generated by Django 4.1 on 2022-09-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_workexperience_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
